// <auto-generated />
using System;
using Leo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leo.Migrations
{
    [DbContext(typeof(AppDbContent))]
    [Migration("20200404121800_AddImgArrInCar")]
    partial class AddImgArrInCar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Leo.Models.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<decimal>("price");

                    b.HasKey("id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Leo.Models.Img", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Carid");

                    b.Property<string>("path")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("Carid");

                    b.ToTable("Img");
                });

            modelBuilder.Entity("Leo.Models.Img", b =>
                {
                    b.HasOne("Leo.Models.Car")
                        .WithMany("img")
                        .HasForeignKey("Carid");
                });
#pragma warning restore 612, 618
        }
    }
}
